# --- Конфігурація для Netlify ---

# Секція [build] визначає налаштування процесу збірки проєкту.
[build]
  # Команда, яка буде виконуватися для збірки сайту.
  # Оскільки наш поточний проєкт складається з чистих HTML, CSS та JS,
  # у нас немає формального кроку збірки. Ця команда є стандартним
  # плейсхолдером на майбутнє.
  command = "npm run build"

# Секція [functions] налаштовує роботу серверних функцій (Serverless Functions).
[functions]
  # Директорія, в якій Netlify буде шукати наші серверні функції.
  # Ми будемо створювати їх у папці /netlify/functions/
  directory = "netlify/functions"
