# --- Конфігурація для Netlify ---

# Секція [functions] налаштовує роботу серверних функцій (Serverless Functions).
# Ми залишаємо її, оскільки вона знадобиться нам для адмін-панелі.
[functions]
  # Директорія, в якій Netlify буде шукати наші серверні функції.
  directory = "netlify/functions"